import type { Metadata } from 'next';
import { lightFont } from './fonts/localFonts'
import Link from 'next/link';
import SmoothScroll from './SmoothScroll';
import './globals.css'

export const metadata: Metadata = {
  title: 'botanical-garden',
  description: 'Generated by create next app',
}

function PathBar() {
  return (
    <div className="fixed w-full z-[99] mix-blend-difference top-[0%] text-white tracking-[.09em]">
      <div className="py-[24px] px-[32px] flex justify-between items-center">
        <Link href="/" className={`${lightFont.className} text-[1.3em]`}>
          Martín Cárdenas
        </Link>

        <div className="ml-auto flex text-[1.3em]">
          <Link href="/">Home</Link>
          <div>
            <span className="text-[1.05em] mx-[20px]">/</span>
            <Link href="/schedule">schedule</Link>
          </div>
          <div>
            <span className="text-[1.05em] mx-[20px]">/</span>
            <Link href="/exploration">exploration</Link>
          </div>
          <div>
            <span className="text-[1.05em] mx-[20px]">/</span>
            <Link href="/blog">blog</Link>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lightFont.className} text-[1vw] font-normal leading-none min-h-[100vh] bg-[#f2f2f2] text-[#030303] box-border`}>
        <header><PathBar /></header>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
